version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "python -m alembic upgrade head && python -m uvicorn app:app --host 0.0.0.0 --port 8000"

  proxy:
    image: easypi/shadowsocks-libev
    env_file:
      - .docker/.env
    command:
      ss-local -s ${PROXY_HOST}
      -p 53712
      -m aes-256-gcm
      -k ${PROXY_PASSWORD}
      -b 0.0.0.0
      -l 1080
      -t 60
      --fast-open

  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    env_file:
      - .docker/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./.docker/nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - .docker/.env
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - static_storage:/data
    env_file:
      - .docker/.env
    command: server /data --console-address :9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_storage:
  static_storage:
